# Python Quick Reference

## 1. import

In [6]:
import numpy as np 
import pandas as pd

## 2.NumPy Arrays

In [ ]:
arr = np.array([10, 20, 30, 40])
matrix = np.array([[1, 2, 3], [4, 5, 6]])

## 3.Pandas

In [7]:
df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Reza", "Mina", "Nima", "Sara"],
    "Age": [25, 30, 28, np.nan, 35, 30],
    "City": ["Tehran", "Shiraz", "Tehran", "Tabriz", "Shiraz", "Shiraz"],
    "Salary": [300, 450, 380, 320, np.nan, 450],
    "Department": ["IT", "Sales", "IT", "HR", "IT", "Sales"]
})

In [8]:
df.head()

   Name   Age    City  Salary Department
0   Ali  25.0  Tehran   300.0         IT
1  Sara  30.0  Shiraz   450.0      Sales
2  Reza  28.0  Tehran   380.0         IT
3  Mina   NaN  Tabriz   320.0         HR
4  Nima  35.0  Shiraz     NaN         IT

In [9]:
df.tail(3)

   Name   Age    City  Salary Department
3  Mina   NaN  Tabriz   320.0         HR
4  Nima  35.0  Shiraz     NaN         IT
5  Sara  30.0  Shiraz   450.0      Sales

In [10]:
df.shape

(6, 5)

In [11]:
df.columns

Index(['Name', 'Age', 'City', 'Salary', 'Department'], dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         5 non-null      float64
 2   City        6 non-null      str
 3   Salary      5 non-null      float64
 4   Department  6 non-null      str
dtypes: float64(2), str(3)
memory usage: 449.0 bytes

In [13]:
df.describe()

             Age      Salary
count   5.000000    5.000000
mean   29.600000  380.000000
std     3.646917   70.356236
min    25.000000  300.000000
25%    28.000000  320.000000
50%    30.000000  380.000000
75%    30.000000  450.000000
max    35.000000  450.000000

In [14]:
df.isna().sum()

Name          0
Age           1
City          0
Salary        1
Department    0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(1)

## 4.Data Cleaning and Preparation

### 4.1 Handling missing Data

In [19]:
float_data=pd.Series([1.2,-3.5,np.nan,0])

In [20]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

#### 4.1.1 Filtering Out Missing Data

In [23]:
data = pd.Series([1,np.nan, 3.5,np.nan,7])

In [24]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

#### 4.1.2 Filling in missing Data

In [27]:
data.fillna(0)

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

### 4.2 Data Tranformation

In [36]:
data2 = pd.DataFrame({"k2":[1,1,1,1,2,2,2,3,3,4]})

#### 4.2.1 Removing Dublicates

In [35]:
data2

   k2
0   1
1   1
2   1
3   1
4   2
5   2
6   2
7   3
8   3
9   4

In [37]:
data.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [ ]:
data.duplicated()